/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginandsignup;
import java.sql.PreparedStatement;
import jaco.mp3.player.MP3Player;
import java.io.File;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet; 
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import com.mysql.jdbc.Driver;

/**
 *
 * @author RASHIKA GUPTA
 */
public class Home extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    private Object Fname;
    public Statement st = null;
    String date;
    public static final String path = "C:\\Users\\RASHIKA GUPTA\\Desktop\\Alarm Clock.mp3";
    MP3Player mp3 = new MP3Player(new File(path));
    
    int flag = 1, flag2 = 0;
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dcDate = new com.toedter.calendar.JDateChooser();
        name_tf = new javax.swing.JTextField();
        Addbtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        DeleteBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reminder");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("             Set Your Daily Reminder");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 0, 700, 60);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Remind me to....");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 90, 120, 30);

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Select Date");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(170, 130, 100, 30);

        dcDate.setBackground(new java.awt.Color(255, 255, 255));
        dcDate.setForeground(new java.awt.Color(102, 102, 102));
        dcDate.setDateFormatString("yyyy-MM-dd");
        dcDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(dcDate);
        dcDate.setBounds(300, 130, 280, 30);

        name_tf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        name_tf.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(name_tf);
        name_tf.setBounds(300, 90, 280, 31);

        Addbtn.setBackground(new java.awt.Color(0, 102, 102));
        Addbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Addbtn.setForeground(new java.awt.Color(255, 255, 255));
        Addbtn.setText("Add");
        Addbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Addbtn);
        Addbtn.setBounds(320, 180, 100, 30);

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Clear");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(440, 180, 100, 30);

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(102, 102, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 230, 670, 140);

        DeleteBtn.setBackground(new java.awt.Color(0, 102, 102));
        DeleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DeleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        DeleteBtn.setText("Delete");
        DeleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteBtn);
        DeleteBtn.setBounds(130, 380, 120, 30);

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Stop");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(360, 380, 110, 30);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Refresh");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(580, 380, 100, 30);

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Your's  Reminder");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 440, 170, 25);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(102, 102, 102));

        ta.setBackground(new java.awt.Color(214, 217, 233));
        ta.setColumns(20);
        ta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ta.setRows(5);
        jScrollPane2.setViewportView(ta);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(180, 440, 330, 40);

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\RASHIKA GUPTA\\Documents\\NetBeansProjects\\LoginAndSignUp\\src\\Icon\\arrow.png")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(20, 20, 50, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
        // TODO add your handling code here:
         
        try{

            String sql = "INSERT INTO reminder"+"(remind_me,date)"+"VALUES (?,?)";

            SimpleDateFormat f = new SimpleDateFormat("yyyy");
            SimpleDateFormat f1 = new SimpleDateFormat("MM");
            SimpleDateFormat f2 = new SimpleDateFormat("dd");

            date = f.format(dcDate.getDate())+"-"+f1.format(dcDate.getDate())+"-"+f2.format(dcDate.getDate());

            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/java_login_signup","root","");
            pst =  con.prepareStatement(sql);
            pst.setString(1,name_tf.getText());
            pst.setString(2, date);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Insert Successfull");
            showTableData();

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Exception "+ex);
        }
    }//GEN-LAST:event_AddbtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        name_tf.setText("");
        dcDate.setCalendar(null);
        showTableData();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        int numberOfRow = jTable1.getSelectedRow();

        TableModel model = jTable1.getModel();

        String n = model.getValueAt(numberOfRow,0).toString();
        String bg = model.getValueAt(numberOfRow,1).toString();

        name_tf.setText(n);
        Date date;
        try {
            date = new SimpleDateFormat("yyyy-MM-dd").parse(""+bg);
            dcDate.setDate(date);
        } catch (ParseException ex) {

        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:

        try {

            String sql = "DELETE FROM reminder WHERE remind_me=?";
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/java_login_signup","root","");
            pst = (PreparedStatement) con.prepareStatement(sql);

            pst.setString(1,name_tf.getText());
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Delete Successfull");
            showTableData();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, Fname);

            JOptionPane.showMessageDialog(this, "!!!!!!!!!! Unsuccessfull Delete");
        }

    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        flag=0;
        mp3.stop();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        flag=1;
        alart();
        showTableData();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Back nt = new Back();
        nt.show();
        dispose();
    
    }//GEN-LAST:event_jButton4ActionPerformed
        public void showTableData(){
        
        try{
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/java_login_signup","root","");
        
            String sql = "SELECT * FROM reminder"; 
            pst = (PreparedStatement) con.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            jTable1.setRowHeight(30);
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"!!!!! Error to show");
        }
        
    }
     
    public void alart(){
        
            long millis=System.currentTimeMillis();  
            java.sql.Date d = new java.sql.Date(millis);  
            String date = d.toString().substring(5);
                
            ArrayList<String> ss = new ArrayList<String>();
        
        for (int i = 0; i < jTable1.getRowCount(); i++) {
                if (date.equals(jTable1.getValueAt(i, 1).toString().substring(5))) {
                    ss.add(jTable1.getValueAt(i, 0).toString());
                }        
        }
        
        ta.setText(""+ss);
        
        Thread t;t = new Thread(){
            public void run() {
                
                for (;;) {
                    
                    int ct=0;
                    long millis=System.currentTimeMillis();
                    java.sql.Date d=new java.sql.Date(millis);
                    
                    String date = d.toString().substring(5);
                    
                    for (int i = 0; i < jTable1.getRowCount(); i++) {
                        if (date.equals(jTable1.getValueAt(i, 1).toString().substring(5))&&flag==1) {                   
                            mp3.play();    
                        }
                        
                        else  
                            ct++;
                    }
                    if (ct==0) {
                        JOptionPane.showMessageDialog(null, "No one");
                    }
                    try {
                        sleep(16000);
                    }catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            }
        };
        t.start();
    }
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbtn;
    private javax.swing.JButton DeleteBtn;
    private com.toedter.calendar.JDateChooser dcDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField name_tf;
    private javax.swing.JTextArea ta;
    // End of variables declaration//GEN-END:variables
}
